default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        types_or: [javascript, jsx, ts, tsx, css, json, yaml, markdown]
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        files: \.js$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        pass_filenames: false
